-- liquibase formatted sql
-- changeset tofik:create-project-tables

CREATE TABLE chat_message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT                                  NOT NULL,
    sender_id  BIGINT                                  NOT NULL,
    message    VARCHAR(1024)                           NOT NULL,
    sent_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_chat_message PRIMARY KEY (id)
);

CREATE TABLE file
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT                                  NOT NULL,
    file_name  VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_file PRIMARY KEY (id)
);

CREATE TABLE project
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024),
    owner_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE project_membership
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id   BIGINT                                  NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    project_role VARCHAR(255)                            NOT NULL,
    joined_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_project_membership PRIMARY KEY (id)
);

CREATE TABLE revision
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_id      BIGINT                                  NOT NULL,
    path_to_file VARCHAR(1024),
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_revision PRIMARY KEY (id)
);

CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE run_history
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    project_id     BIGINT                                  NOT NULL,
    compile_output VARCHAR(255),
    run_output     VARCHAR(255),
    success        BOOLEAN,
    started_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    finished_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_run_history PRIMARY KEY (id)
);

CREATE TABLE test_case
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id      BIGINT                                  NOT NULL,
    input_data      TEXT                                    NOT NULL,
    expected_output TEXT                                    NOT NULL,
    description     VARCHAR(1024),
    CONSTRAINT pk_test_case PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    email_verified BOOLEAN                                 NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_verification_token PRIMARY KEY (id)
);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verification_token_token UNIQUE (token);

ALTER TABLE chat_message
    ADD CONSTRAINT FK_CHAT_MESSAGE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE chat_message
    ADD CONSTRAINT FK_CHAT_MESSAGE_ON_SENDER FOREIGN KEY (sender_id) REFERENCES "user" (id);

ALTER TABLE file
    ADD CONSTRAINT FK_FILE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_membership
    ADD CONSTRAINT FK_PROJECT_MEMBERSHIP_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_membership
    ADD CONSTRAINT FK_PROJECT_MEMBERSHIP_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_OWNER FOREIGN KEY (owner_id) REFERENCES "user" (id);

ALTER TABLE revision
    ADD CONSTRAINT FK_REVISION_ON_FILE FOREIGN KEY (file_id) REFERENCES file (id);

ALTER TABLE run_history
    ADD CONSTRAINT FK_RUN_HISTORY_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE run_history
    ADD CONSTRAINT FK_RUN_HISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE test_case
    ADD CONSTRAINT FK_TEST_CASE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATION_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);

